apiVersion: v1
kind: Service
metadata:
  name: code-sample
  labels:
    app: code-sample
spec:
  selector:
    app: code-sample
  ports:
    - port: 8080
      protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: code-sample-ac
  labels:
    app: code-sample
---
#apiVersion: rbac.authorization.k8s.io/v1beta1
#kind: RoleBinding
#metadata:
#  name: myBinding
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: Role
#  name: code-sample-a
#subjects:
#- kind: ServiceAccount
#  name: code-sample-ac
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-sample-deployment
  labels:
    app: code-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-sample
  template:
    metadata:
      labels:
        app: code-sample
    spec:
      serviceAccountName: code-sample-ac
      containers:
      - name: code-sample
        image: registry.hub.docker.com/gykmegazone/code:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 500m
     #nodeSelector:
     #   nodeType: worker1
